# Generated by Django 5.2.1 on 2025-06-18 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0003_remove_doador_idade_remove_receptor_idade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroDistribuicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('endereço', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('estoque', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orgao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('Orgão', 'Orgão'), ('Tecido', 'Tecido'), ('Sangue', 'Sangue')], max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='doador',
            name='estado_civil',
            field=models.CharField(choices=[('Solteiro', 'Solteiro'), ('Solteira', 'Solteira'), ('Casado', 'Casado'), ('Casada', 'Casada'), ('Divorciado', 'Divorciado'), ('Divorciada', 'Divorciada'), ('Viúvo', 'Viúvo'), ('Viúva', 'Viúva'), ('União Estável', 'União Estável')], max_length=20),
        ),
        migrations.AlterField(
            model_name='doador',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1),
        ),
        migrations.AlterField(
            model_name='receptor',
            name='estado_civil',
            field=models.CharField(choices=[('Solteiro', 'Solteiro'), ('Solteira', 'Solteira'), ('Casado', 'Casado'), ('Casada', 'Casada'), ('Divorciado', 'Divorciado'), ('Divorciada', 'Divorciada'), ('Viúvo', 'Viúvo'), ('Viúva', 'Viúva'), ('União Estável', 'União Estável')], max_length=20),
        ),
        migrations.AlterField(
            model_name='receptor',
            name='posicao_lista_espera',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='receptor',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1),
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('tipo_sanguineo', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('data_nascimento', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('profissao', models.CharField(max_length=100)),
                ('estado_natal', models.CharField(max_length=2)),
                ('cidade_natal', models.CharField(max_length=100)),
                ('estado_residencia', models.CharField(max_length=2)),
                ('cidade_residencia', models.CharField(max_length=100)),
                ('estado_civil', models.CharField(choices=[('Solteiro', 'Solteiro'), ('Solteira', 'Solteira'), ('Casado', 'Casado'), ('Casada', 'Casada'), ('Divorciado', 'Divorciado'), ('Divorciada', 'Divorciada'), ('Viúvo', 'Viúvo'), ('Viúva', 'Viúva'), ('União Estável', 'União Estável')], max_length=20)),
                ('contato_emergencia', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
