# Generated by Django 5.2.1 on 2025-06-23 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0005_orgao_descricao_alter_orgao_tipo_doacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centrodistribuicao',
            name='endereço',
        ),
        migrations.RemoveField(
            model_name='centrodistribuicao',
            name='telefone',
        ),
        migrations.AddField(
            model_name='doador',
            name='orgaos_que_deseja_doar',
            field=models.ManyToManyField(blank=True, to='meuapp.orgao'),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='cpf',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='doador',
            name='cpf',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='receptor',
            name='cpf',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
