# Generated by Django 5.2.1 on 2025-06-24 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0006_remove_centrodistribuicao_endereço_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doador',
            name='intencao_doar',
            field=models.BooleanField(default=False),
        ),
    ]
